---
parent: "api_v1_system-settings"
name: "api_v1_system-settings_get_path_param__MySQL_page"
description: null
type: "SUITE"
endpoint: "/api/v1/system-settings?page={{@MySQLSQLInjections}}"
method: "GET"
auth: "Default"
headers:
- "Accept: application/json"
- "Content-Type: application/json"
testCases: []
assertions: []
tags:
- "V1"
authors:
- "FX Bot"
category: null
severity: null
inactive: false
policies:
  initExec: "Request"
  cleanupExec: "Request"
  logger: "DEBUG"
  timeoutSeconds: 300
  repeatOnFailure: 0
  repeat: 0
  repeatModule: "@MySQLSQLInjections"
  repeatDelay: 0
