---
parent: "api_v1_system-settings"
name: "api_v1_system-settings_put_"
description: null
type: "SUITE"
endpoint: "/api/v1/system-settings"
method: "PUT"
auth: "INVALID_AUTH"
headers:
- "Accept: application/json"
- "Content-Type: application/json"
testCases: []
assertions: []
tags:
- "V1"
authors:
- "FX Bot"
category: null
severity: null
inactive: false
policies: null
